.PHONY: all lint test cover

all:
	go build -o main cmd/main.go

lint:
	go fmt ./...
	golint ./...
	go vet ./...
	errcheck ./...

test:
	go test -v -race ./...

cover:
	go test -coverprofile=/tmp/core_profile.out ./...
	go tool cover -html=/tmp/core_profile.out
